# Generated by Django 5.0.7 on 2024-07-27 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montoTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numeroCuotas', models.IntegerField()),
                ('fechaAdquisicion', models.DateField()),
                ('pagada', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Pago.entidad')),
            ],
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaVencimiento', models.DateField()),
                ('pagada', models.BooleanField(default=False)),
                ('voucher', models.ImageField(blank=True, null=True, upload_to='vouchers/')),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Pago.deuda')),
            ],
        ),
    ]
