# Generated by Django 5.0.7 on 2024-07-27 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pago', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='deuda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='Pago.deuda'),
        ),
    ]
